plugins {
    id 'com.enonic.xp.app'
    id 'maven-publish'
}

dependencies {
    implementation xplibs.api.core
    implementation xplibs.api.portal
    include xplibs.portal
    include xplibs.content
}

repositories {
    mavenLocal()
    mavenCentral()
    xp.enonicRepo()
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = "${group}"
            artifactId = "${projectName}"
            version = "${version}"

            from components.java
        }
    }
}

wrapper {
    gradleVersion = '9.5.0'
    distributionType = Wrapper.DistributionType.BIN
}