# Gradle Project settings
projectName = security-headers
version = 4.0.0

# XP App values
displayName = Security Headers
appName = no.bouvet.app.securityheaders
vendorName = Bouvet
vendorUrl = https://www.bouvet.no
xpVersion = 8.0.3

# Settings for publishing to a Maven repo
group = com.github.bouvet-apps
